Rails.application.config.assets.precompile += %w( mercury_assets/mercury.js )
Rails.application.config.assets.precompile += %w( cards.js )
Rails.application.config.assets.precompile += %w( area.js )
Rails.application.config.assets.precompile += %w( mapbox.js )
Rails.application.config.assets.precompile += %w( jquery.min.js )
Rails.application.config.assets.precompile += %w( d3.v3.min.js )
Rails.application.config.assets.precompile += %w( pages.js )
