_prefs: 
  baselayer: ''
  mapid: boundround.d822e9da
  saveCenter: false
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85
  - 180
  - 85
center: 
  - 0
  - 0
  - 3
description: ''
format: "png8:m=h:c=64"
interactivity_layer: ''
layers: null
maxzoom: 18
minzoom: 0
name: BR English Max Zoom 18
source: "mapbox:///mapbox.mapbox-streets-v5"
styles: 
  - vars.mss
  - bg.mss
  - road.mss
  - label.mss
  - poi_classic.mss
template: ''
